name: Flyway Migrations

on:
  push:
    branches:
      - main

jobs:
  flyway-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Install Flyway
        run: |
          curl -sSL "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.0.1/flyway-commandline-8.0.1-linux-x64.tar.gz" -o flyway.tar.gz
          tar -xzf flyway.tar.gz
          export PATH="${PWD}/flyway-8.0.1:${PATH}"

      - name: Configure Flyway
        run: |
          echo "flyway.url=${{ secrets.LIVE_DB_URL }}" >> flyway-8.0.1/conf/flyway.conf
          echo "flyway.user=${{ secrets.LIVE_DB_USER }}" >> flyway-8.0.1/conf/flyway.conf
          echo "flyway.password=${{ secrets.LIVE_DB_PASSWORD }}" >> flyway-8.0.1/conf/flyway.conf
          echo "flyway.schemas=public" >> flyway-8.0.1/conf/flyway.conf

      - name: Run Flyway Migrations
        run: flyway-8.0.1/flyway migrate -locations=filesystem:migration
